fix: account.ts update getToken method to use cheerio API
Due to error in current github action:
```
  26 |       token = element.getAttribute("value") as string
  27 |     }
  28 |   }).transform(input)
  29 |
  30 |   if (!token) {
  31 |     throw new Error("could not parse csrf token")
                     ^
  error: could not parse csrf token
        at getToken (/home/runner/work/_actions/ondreian/simu-rewards/v1/rewards/account.ts:31:15)
        at async login (/home/runner/work/_actions/ondreian/simu-rewards/v1/rewards/account.ts:38:23)
        at async claimAccountRewards (/home/runner/work/_actions/ondreian/simu-rewards/v1/rewards/account.ts:77:23)
        at async claim (/home/runner/work/_actions/ondreian/simu-rewards/v1/rewards/index.ts:25:31)
```
Update to use cheerio API instead of Cloudflare Workers API in `getToken` method.